<?php

namespace Hotmeteor\Regex;

use Illuminate\Support\ServiceProvider;

class RegexServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}